import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

import { Roboto, Inter } from "next/font/google";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Corgi Homeplan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-screen flex-col items-center justify-between mx-auto ">
          {children}
        </main>
      </body>
    </html>
  );
}
