import "./globals.css";
import "flowbite";
import { Roboto, Poppins } from "next/font/google";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
export const metadata = {
  title: "Corgi Homeplan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <main className="flex w-screen justify-center">{children}</main>
        <Footer />
        <script
          defer={true}
          src="https://cdn.jsdelivr.net/npm/flowbite/dist/flowbite.js"
        ></script>
      </body>
    </html>
  );
}
